### ISSUE TITLE
Worse performance on Iris 1.2.7+ vs pre 1.2.6 Iris when looking away from the sun.

### ISSUE THREAD

**Issue by PlanetSun3** [IrisShaders/Iris#1626]
### What happened?

1. Go into any world
2. /gamerule DoDaylightCycle false
3. /time set 0
4. Look away from the sun or do /tp @s 0 128 0 90 0 (but make sure you load in all the chunks before you look away from the sun)
Repeat steps 1-4 with Iris 1.2.6. Notice how the fps is considerably higher with 1.2.6 than 1.2.8. I also noticed that the amount of shadow terrain jumped from 2400 to 4400, which I am absolute certain is causing this loss in framerate. Same mods used for both versions, apart from updated indium and sodium extra versions so they could work with 0.4.3+

### Screenshots

![2022-09-04_19 01 58](https://user-images.githubusercontent.com/61162198/188338840-68197120-c19a-45c1-bf1c-33dcdd96b119.png)
![2022-09-04_19 05 14](https://user-images.githubusercontent.com/61162198/188338845-9e28eb2e-a08d-4250-95f3-5adff2ce25e1.png)

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/9485744/latest.log)

### Minecraft Version

1.19.2

### Iris Version

1.2.6 and 1.2.8 (same bug with 1.2.8 also exists in 1.2.7)

### Operating System

Windows 10

### What is your GPU?

GTX 1080

**Comment by coderbot16** [comment]
Please test again with Iris 1.3.1 - this issue should be resolved in 1.3

**Comment by PlanetSun3** [comment]
1.3.1 had practically the same results as 1.2.8 even with the refactored shadow render targets. 
![2022-09-14_20 52 01](https://user-images.githubusercontent.com/61162198/190294659-7fa01e84-6738-4525-8919-f7cc62d7e18c.png)

**Comment by IMS212** [comment]
Cannot replicate on 1.4.0 (latest commit), please try without any other mods.
![2022-10-30_16 30 20](https://user-images.githubusercontent.com/31803019/198907266-d9369b53-c215-4c3c-be55-d0bf543ebf3b.png)

**Comment by IMS212** [comment]
We've found the cause of this to be a seemingly rogue check in the Frustum calculation that incorrectly marks intersecting chunks as inside. For now, we've disabled the check, fixing the chunk count at a slight performance cost.

**Comment by PlanetSun3** [comment]
Just retested using 1.4.1 and I'm still getting double chunk count on the shadows, same position as before. It might have decreased by a few hundred but nowhere near the 2500 or so on 1.2.6 and before.

**Comment by IMS212** [comment]
Yep; “1.4.1’ ended up being a hotfix update to 1.4.0 that didn’t include the final fix.

**Comment by IMS212** [comment]
Yep. 1.4.2 also ended up being a hotfix.

when it’s fixed, we will close the issue,

**Comment by PlanetSun3** [comment]
Yep, just tested with 1.4.3 and it's back to normal. Thanks!
