### ISSUE TITLE
Some shader packs fail to compile on 1.17 on Intel Windows drivers

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#441]
Relevant error, happens with `composite.fsh` / `composite.vsh` in all versions of Sildur's Vibrant Shaders:

> Attribute Position is bound to generic attribute 0, but gl_Vertex is also used

I don't have this hardware to test with, it needs to be verified whether this happens on the current latest commit of the 1.17 branch.

**Comment by AlsoNiko** [comment]
Issue needs to be put on hold for now, as the common denominator is everyone who had said issue got it from the installer, which has yet to see intel and mesa fixes pushed.

**Comment by coderbot16** [comment]
Would be good to have confirmation that anyone observing this on older versions is no longer observing it with the latest commit.

**Comment by AlsoNiko** [comment]
Currently trying to see that, and well it looks good I have not had a chance to check on legacy intel drivers, so I'm not sure yet

**Comment by Viruzaum** [comment]
Can confirm it still happens in [f06a69d](https://github.com/IrisShaders/Iris/commit/f06a69db23e3440bda009aa3f74bdb2ee7146e73).

Log: https://paste.ee/p/hT6Wl.

**Comment by AlsoNiko** [comment]
Issue has been further confirmed with the Intel HD 4000, seems to affect 1.1.1 but not 1.1.0, looking for logs

**Comment by AlsoNiko** [comment]
[latest (1).log](https://github.com/IrisShaders/Iris/files/6928038/latest.1.log)
relavent log using sodium 0.3 and iris 1.1.1

**Comment by IMS212** [comment]
Reviving this: could we just rename gl_Vertex to iris_Vertex? This issue seems to be the driver mistakenly thinking gl_Vertex is used just because it has the text "gl_Vertex".

**Comment by coderbot16** [comment]
I don't know. The fact that the drivers are raising such an error message in the first place probably indicates that they're seriously buggy, so I can't really predict anything.

**Comment by 0ASLAN-dev0** [comment]
still getting this error

**Comment by Brayan0000** [comment]
> still getting this error

Same

**Comment by Brayan0000** [comment]
i find out that it works fine in linux
